# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - caritas-webapp

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_42D7FF5757F64F1F8BCD1D54B683DFEA }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_874D5106878E40AB9846E847267F1D23 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_448AD6ABAAC142459701EC3BEB2767E0 }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'caritas-webapp'
        slot-name: 'Production'
        package: .

# name: CI Caritas

# on:
#   push:
#     branches:
#     - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [ 20.x ]

#     steps:
#     - name: Checkout código
#       uses: actions/checkout@v3

#     - name: Configurar Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'

#     - name: Instalar dependências
#       run: npm install

#     # - name: Rodar testes
#     #   run: npm test

#     - name: Build da aplicação
#       run: npm run build

#     - name: Salvar artefatos do build
#       uses: actions/upload-artifact@v3
#       with:
#         name: dist
#         path: .output/

#     - name: Deploy to Azure
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: caritas-webapp
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         package: .
