name: CI Caritas

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar dependências
      run: npm install

    - name: Rodar testes
      run: npm test

    - name: Build da aplicação
      run: npm run build

    - name: Salvar artefatos do build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: .output/
